volumes:
  db_volume:

services:
  web:
    build: .docker/php
    volumes:
      - ./projdir:/var/www/html
    environment:
      VIRTUAL_HOST: "api.local.bot3.com"
      TZ: Asia/Tokyo
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d"
    ports:
      - '8080:80'
  
  db:
    image: mysql:8.0
    volumes:
      - db_volume:/var/lib/mysql
      - .docker/mysql/my.cnf:/etc/mysql/conf.d/custom.cnf
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bot3_local_db
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo

networks:
  default:
    name: nginx-proxy
    external: true
