volumes:
  db_volume:

services:
  web:
    build: ./docker/php
    volumes:
      - ./projdir:/var/www/html
    environment:
      VIRTUAL_HOST: "api.local.bot3.com"
      TZ: Asia/Tokyo
    ports:
      - 8888:80
  
  db:
    build: ./docker/mysql
    volumes:
      - db_volume:/var/lib/mysql
    ports:
      - 3331:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bot3_local_db
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo

networks:
  default:
    name: nginx-proxy
    external: true
