on:
  push:
    branches: [ "main" ]


jobs:
  laravel-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_DOMAIN }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PUBLIC_KEY }}
          script: |
            cd docker-production
            docker container stop laravel9_linebot
            cd ../linebot
            git fetch origin main
            git reset --hard origin
            chmod -R 775 projdir
            cd projdir
            echo "${{ secrets.LARAVEL_ENV }}" > .env
            cd ../../docker-production
            docker compose -f ./docker-compose.yml up -d --build --force-recreate
            